import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { test } from "node:test";

// The JOVO delivery-alert sound (generated by scripts/generate-alert-sound.mjs). It has to be
// loud, short and audible on a phone speaker over road noise, and these properties are what make
// it so, so a regenerated or replaced file is held to them.
const file = path.resolve(__dirname, "../../assets/sounds/jovo_delivery.wav");
const wav = readFileSync(file);

function parse() {
  assert.equal(wav.toString("ascii", 0, 4), "RIFF");
  assert.equal(wav.toString("ascii", 8, 12), "WAVE");
  assert.equal(wav.readUInt16LE(20), 1, "linear PCM: the format iOS accepts for custom notification sounds");
  const channels = wav.readUInt16LE(22);
  const sampleRate = wav.readUInt32LE(24);
  const bits = wav.readUInt16LE(34);
  assert.equal(wav.toString("ascii", 36, 40), "data");
  const dataLength = wav.readUInt32LE(40);
  const samples = new Float64Array(dataLength / 2);
  for (let index = 0; index < samples.length; index += 1) samples[index] = wav.readInt16LE(44 + index * 2) / 32768;
  return { channels, sampleRate, bits, samples };
}

function fftMagnitudes(signal: Float64Array): { magnitudes: Float64Array; size: number } {
  let size = 1;
  while (size < signal.length) size *= 2;
  const re = new Float64Array(size);
  const im = new Float64Array(size);
  re.set(signal);
  for (let i = 1, j = 0; i < size; i += 1) {
    let bit = size >> 1;
    for (; j & bit; bit >>= 1) j ^= bit;
    j ^= bit;
    if (i < j) [re[i], re[j]] = [re[j], re[i]];
  }
  for (let length = 2; length <= size; length <<= 1) {
    const angle = (-2 * Math.PI) / length;
    for (let start = 0; start < size; start += length) {
      for (let k = 0; k < length / 2; k += 1) {
        const wr = Math.cos(angle * k);
        const wi = Math.sin(angle * k);
        const a = start + k;
        const b = a + length / 2;
        const tr = re[b] * wr - im[b] * wi;
        const ti = re[b] * wi + im[b] * wr;
        re[b] = re[a] - tr;
        im[b] = im[a] - ti;
        re[a] += tr;
        im[a] += ti;
      }
    }
  }
  const magnitudes = new Float64Array(size / 2);
  for (let index = 0; index < magnitudes.length; index += 1) magnitudes[index] = Math.hypot(re[index], im[index]);
  return { magnitudes, size };
}

test("the alert sound is a mono 16-bit PCM WAV, the format both platforms take", () => {
  const { channels, bits, sampleRate } = parse();
  assert.equal(channels, 1);
  assert.equal(bits, 16);
  assert.ok(sampleRate >= 22_050);
});

test("the alert lasts long enough to notice and short enough not to be a ringtone (iOS caps custom sounds at 30 s)", () => {
  const { samples, sampleRate } = parse();
  const seconds = samples.length / sampleRate;
  assert.ok(seconds >= 2 && seconds <= 6, `duration ${seconds.toFixed(2)} s`);
});

test("the alert is loud: peaks near full scale and a high average level", () => {
  const { samples } = parse();
  let peak = 0;
  for (const value of samples) peak = Math.max(peak, Math.abs(value));
  const rms = Math.sqrt(samples.reduce((sum, value) => sum + value * value, 0) / samples.length);
  const peakDb = 20 * Math.log10(peak);
  const rmsDb = 20 * Math.log10(rms);
  assert.ok(peakDb >= -3 && peakDb <= -0.1, `peak ${peakDb.toFixed(1)} dBFS (must be loud but not clipped)`);
  assert.ok(rmsDb >= -14, `RMS ${rmsDb.toFixed(1)} dBFS: a quiet-sounding alert gets lost in a moving car`);
});

test("the energy sits where a phone speaker is strong and road noise is weak: little below 600 Hz, most between 1 and 6 kHz", () => {
  const { samples, sampleRate } = parse();
  const { magnitudes, size } = fftMagnitudes(samples);
  const binHz = sampleRate / size;
  let total = 0;
  let low = 0;
  let band = 0;
  for (let index = 1; index < magnitudes.length; index += 1) {
    const energy = magnitudes[index] ** 2;
    const hz = index * binHz;
    total += energy;
    if (hz < 600) low += energy;
    if (hz >= 1_000 && hz <= 6_000) band += energy;
  }
  assert.ok(low / total < 0.05, `${((low / total) * 100).toFixed(1)}% of the energy is below 600 Hz`);
  assert.ok(band / total > 0.8, `${((band / total) * 100).toFixed(1)}% of the energy is in 1-6 kHz`);
});

test("the sound ends without a click, so it does not pop when it is cut off", () => {
  const { samples } = parse();
  assert.ok(Math.abs(samples[samples.length - 1]) < 0.01);
});

test("the file name is a valid Android raw resource (lowercase letters, digits, underscore) and matches the API", () => {
  const name = path.basename(file);
  assert.match(name, /^[a-z0-9_]+\.wav$/);
  const api = readFileSync(path.resolve(__dirname, "../../../api/src/notifications/push-presentation.ts"), "utf8");
  assert.ok(api.includes(`"${name}"`), "the API names a different sound file than the one bundled in the app");
});
